apiVersion: cfzt.reid.ee/v1alpha1
kind: CloudflareTunnel
metadata:
  labels:
    app.kubernetes.io/name: cfzt-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudflaretunnel-sample
spec:
  # TODO(user): Add fields here
