//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPolicyRef) DeepCopyInto(out *AccessPolicyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicyRef.
func (in *AccessPolicyRef) DeepCopy() *AccessPolicyRef {
	if in == nil {
		return nil
	}
	out := new(AccessPolicyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessSpec) DeepCopyInto(out *AccessSpec) {
	*out = *in
	out.PolicyRef = in.PolicyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessSpec.
func (in *AccessSpec) DeepCopy() *AccessSpec {
	if in == nil {
		return nil
	}
	out := new(AccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareExposure) DeepCopyInto(out *CloudflareExposure) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareExposure.
func (in *CloudflareExposure) DeepCopy() *CloudflareExposure {
	if in == nil {
		return nil
	}
	out := new(CloudflareExposure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareExposure) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareExposureList) DeepCopyInto(out *CloudflareExposureList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareExposure, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareExposureList.
func (in *CloudflareExposureList) DeepCopy() *CloudflareExposureList {
	if in == nil {
		return nil
	}
	out := new(CloudflareExposureList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareExposureList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareExposureSpec) DeepCopyInto(out *CloudflareExposureSpec) {
	*out = *in
	out.TunnelRef = in.TunnelRef
	if in.SourceRef != nil {
		in, out := &in.SourceRef, &out.SourceRef
		*out = new(SourceRef)
		**out = **in
	}
	if in.Origin != nil {
		in, out := &in.Origin, &out.Origin
		*out = new(OriginSpec)
		**out = **in
	}
	out.Access = in.Access
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareExposureSpec.
func (in *CloudflareExposureSpec) DeepCopy() *CloudflareExposureSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareExposureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareExposureStatus) DeepCopyInto(out *CloudflareExposureStatus) {
	*out = *in
	out.Cloudflare = in.Cloudflare
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareExposureStatus.
func (in *CloudflareExposureStatus) DeepCopy() *CloudflareExposureStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareExposureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnel) DeepCopyInto(out *CloudflareTunnel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnel.
func (in *CloudflareTunnel) DeepCopy() *CloudflareTunnel {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareTunnel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelList) DeepCopyInto(out *CloudflareTunnelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareTunnel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelList.
func (in *CloudflareTunnelList) DeepCopy() *CloudflareTunnelList {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareTunnelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelSpec) DeepCopyInto(out *CloudflareTunnelSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	out.Dns = in.Dns
	in.Cloudflared.DeepCopyInto(&out.Cloudflared)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelSpec.
func (in *CloudflareTunnelSpec) DeepCopy() *CloudflareTunnelSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelStatus) DeepCopyInto(out *CloudflareTunnelStatus) {
	*out = *in
	out.TokenSecretRef = in.TokenSecretRef
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]RouteStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelStatus.
func (in *CloudflareTunnelStatus) DeepCopy() *CloudflareTunnelStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflaredSpec) DeepCopyInto(out *CloudflaredSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflaredSpec.
func (in *CloudflaredSpec) DeepCopy() *CloudflaredSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflaredSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsSecretKeys) DeepCopyInto(out *CredentialsSecretKeys) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsSecretKeys.
func (in *CredentialsSecretKeys) DeepCopy() *CredentialsSecretKeys {
	if in == nil {
		return nil
	}
	out := new(CredentialsSecretKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsSecretRef) DeepCopyInto(out *CredentialsSecretRef) {
	*out = *in
	out.Keys = in.Keys
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsSecretRef.
func (in *CredentialsSecretRef) DeepCopy() *CredentialsSecretRef {
	if in == nil {
		return nil
	}
	out := new(CredentialsSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsSpec) DeepCopyInto(out *DnsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsSpec.
func (in *DnsSpec) DeepCopy() *DnsSpec {
	if in == nil {
		return nil
	}
	out := new(DnsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposureCloudflareStatus) DeepCopyInto(out *ExposureCloudflareStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposureCloudflareStatus.
func (in *ExposureCloudflareStatus) DeepCopy() *ExposureCloudflareStatus {
	if in == nil {
		return nil
	}
	out := new(ExposureCloudflareStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginSpec) DeepCopyInto(out *OriginSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginSpec.
func (in *OriginSpec) DeepCopy() *OriginSpec {
	if in == nil {
		return nil
	}
	out := new(OriginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteStatus) DeepCopyInto(out *RouteStatus) {
	*out = *in
	in.LastWrittenAt.DeepCopyInto(&out.LastWrittenAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteStatus.
func (in *RouteStatus) DeepCopy() *RouteStatus {
	if in == nil {
		return nil
	}
	out := new(RouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceRef) DeepCopyInto(out *SourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceRef.
func (in *SourceRef) DeepCopy() *SourceRef {
	if in == nil {
		return nil
	}
	out := new(SourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenSecretRef) DeepCopyInto(out *TokenSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenSecretRef.
func (in *TokenSecretRef) DeepCopy() *TokenSecretRef {
	if in == nil {
		return nil
	}
	out := new(TokenSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelRef) DeepCopyInto(out *TunnelRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelRef.
func (in *TunnelRef) DeepCopy() *TunnelRef {
	if in == nil {
		return nil
	}
	out := new(TunnelRef)
	in.DeepCopyInto(out)
	return out
}
