apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cfzt-operator.fullname" . }}
  namespace: {{ include "cfzt-operator.namespace" . }}
  labels:
    {{- include "cfzt-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cfzt-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cfzt-operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "cfzt-operator.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          image: {{ include "cfzt-operator.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --health-probe-bind-address={{ .Values.healthProbe.bindAddress }}
            {{- if .Values.metrics.enabled }}
            - --metrics-bind-address={{ .Values.metrics.bindAddress }}
            - --metrics-secure={{ .Values.metrics.secure }}
            {{- end }}
            - --leader-elect={{ .Values.leaderElection.enabled }}
            - --zap-log-level={{ .Values.logLevel }}
          ports:
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: 8443
              protocol: TCP
            {{- end }}
            - name: probe
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: probe
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: probe
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
